// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttmnyblqqtzeswecqeln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0bW55YmxxcXR6ZXN3ZWNxZWxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MDYzNTYsImV4cCI6MjA2MDk4MjM1Nn0.g7GLwM4evIXUwfRnB5-ZOFWZPS_pPXeyU3yr7fp_q24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);